### ISSUE TITLE
Why is this "stupid" and "shitty"? 

### ISSUE THREAD

**Issue by andrewdelprete** [francesco-strazzullo/js-proxies-ui-framework#1]
I think you did a great job and your project / write up has helped me understand Proxies. Just wanted to know why you thought this was a bad idea?

**Comment by francesco-strazzullo** [comment]
Thank you! In my opinion it's not shitty as "idea" but the quality of the code it's not what you expect from a real framework. It's just that! I'm also creating a JavaScript Object validator [library](https://github.com/francesco-strazzullo/easy-checker) using Proxies.

**Comment by andrewdelprete** [comment]
Awesome man good to hear!
